# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django_email_queue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Posted')], default=django_email_queue.models.QueuedEmailMessageStatus(0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('posted', models.DateTimeField(blank=True, null=True)),
                ('encoding', models.CharField(blank=True, max_length=15, null=True)),
                ('from_email', models.CharField(max_length=300)),
                ('to', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('reply_to', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
