# Generated by Django 4.1.4 on 2023-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_email_queue', '0003_auto_20180504_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedemailmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
